cmake_minimum_required(VERSION 4.0)
set(GAME_NAME hl2) # !SOURCESDK
#set(GAME_NAME mod_hl2) # SOURCESDK
target_include_directories(client PUBLIC hl2 ../shared/hl2 ../../public)
target_compile_definitions(client PUBLIC HL2_CLIENT_DLL)
target_sources(client PUBLIC
        hud_chat.cpp
        c_team_objectiveresource.cpp

        # hl2
        ../shared/hl2/basehlcombatweapon_shared.cpp
		../shared/hl2/achievements_hl2.cpp
		hl2/c_antlion_dust.cpp
		hl2/c_ar2_explosion.cpp
		hl2/c_barnacle.cpp
		hl2/c_barney.cpp
		hl2/c_basehelicopter.cpp
		hl2/c_basehelicopter.h
		hl2/c_basehlcombatweapon.cpp
		hl2/c_basehlcombatweapon.h
		hl2/c_basehlplayer.cpp
		hl2/c_basehlplayer.h
		hl2/c_citadel_effects.cpp
		hl2/c_corpse.cpp
		hl2/c_corpse.h
		hl2/c_env_alyxtemp.cpp
		hl2/c_env_headcrabcanister.cpp
		hl2/c_env_starfield.cpp
		hl2/c_func_tankmortar.cpp
		hl2/c_hl2_playerlocaldata.cpp
		hl2/c_hl2_playerlocaldata.h
		hl2/c_info_teleporter_countdown.cpp
		hl2/c_npc_antlionguard.cpp
		hl2/c_npc_combinegunship.cpp
		hl2/c_npc_manhack.cpp
		hl2/c_npc_rollermine.cpp
		hl2/c_plasma_beam_node.cpp
		hl2/c_prop_combine_ball.cpp
		hl2/c_prop_combine_ball.h
		hl2/c_rotorwash.cpp
		hl2/c_script_intro.cpp
		../shared/script_intro_shared.cpp
		hl2/c_strider.cpp
		hl2/c_te_concussiveexplosion.cpp
		hl2/c_te_flare.cpp
		hl2/c_thumper_dust.cpp
		hl2/c_vehicle_airboat.cpp
		hl2/c_vehicle_cannon.cpp
		hl2/c_vehicle_crane.cpp
		hl2/c_vehicle_crane.h
		hl2/c_vehicle_prisoner_pod.cpp
		hl2/c_weapon__stubs_hl2.cpp
		hl2/c_weapon_crossbow.cpp
		hl2/c_weapon_physcannon.cpp
		hl2/c_weapon_stunstick.cpp
		../shared/hl2/citadel_effects_shared.h
		hl2/clientmode_hlnormal.cpp
		hl2/clientmode_hlnormal.h
		death.cpp
		../shared/hl2/env_headcrabcanister_shared.cpp
		../shared/hl2/env_headcrabcanister_shared.h
		hl2/fx_antlion.cpp
		hl2/fx_bugbait.cpp
		hl2/fx_hl2_impacts.cpp
		hl2/fx_hl2_tracers.cpp
		hl2/hl2_clientmode.cpp
		../shared/hl2/hl2_gamerules.cpp
		../shared/hl2/hl2_gamerules.h
		../shared/hl2/hl2_shareddefs.h
		../shared/hl2/hl2_usermessages.cpp
		../shared/hl2/hl_gamemovement.cpp
		../shared/hl2/hl_gamemovement.h
		hl2/hl_in_main.cpp
		hl2/hl_prediction.cpp
		hl2/hud_ammo.cpp
		hl2/hud_battery.cpp
		hl2/hud_blood.cpp
		hl2/hud_credits.cpp
		hl2/hud_damageindicator.cpp
		hl2/hud_flashlight.cpp
		hl2/hud_health.cpp
		hl2/hud_poisondamageindicator.cpp
		hud_posture.cpp
		hl2/hud_quickinfo.cpp
		hud_squadstatus.cpp
		hl2/hud_suitpower.cpp
		hl2/hud_suitpower.h
		hl2/hud_weaponselection.cpp
		hl2/hud_zoom.cpp
		hl2/shieldproxy.cpp
		hl2/vgui_rootpanel_hl2.cpp
		episodic/c_vort_charge_token.cpp
)